{
 "title": "Kubernetes Jobs Monitor",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(container_memory_working_set_bytes{container=\"main\"}, namespace)"
   },
   {
    "name": "job_pod",
    "label": "Job / Pod",
    "query": "label_values(container_memory_working_set_bytes{namespace=\"$namespace\", container=\"main\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Пиковая память (Max RAM)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$job_pod\", container=\"main\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Пиковый CPU (Max Cores)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(max_over_time(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$job_pod\", container=\"main\"}[30s])[$__range:]))"
    }
   ]
  },
  {
   "title": "Профиль потребления RAM во времени",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$job_pod\", container=\"main\"}",
     "legendFormat": "{{pod}} ({{container}})"
    }
   ]
  },
  {
   "title": "Профиль потребления CPU во времени",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", pod=\"$job_pod\", container=\"main\"}[30s])",
     "legendFormat": "{{pod}} ({{container}})"
    }
   ]
  }
 ]
}