datamart {
  db {
    host = "localhost"
    host = ${?DB_HOST}
    
    port = "5432"
    port = ${?PORT}
    
    db_name = "gpadmin"
    db_name = ${?DB_NAME}
    
    user = "gpadmin"
    user = ${?POSTGRES_USER}
    
    password = ""
    password = ${?POSTGRES_PASSWORD}
  }

  tables {
    raw = "products_raw"
    features = "products_features"
    predictions = "products_predictions"
    clustered = "products_clustered"
  }

  spark {
    app_name = "Greenplum_DataMart_Scala"
    master = "local[*]"
    
    settings {
      "spark.driver.memory" = "2g"
      "spark.driver.cores" = "2"
      "spark.sql.shuffle.partitions" = "10"
      "spark.driver.memoryOverhead" = "512m"
    }
  }
}